"""Operator directory with fiscal year configuration and metadata.

This module contains the canonical registry of telecom operators,
their fiscal year configurations, earnings calendars, and operator groups.
"""

# ============================================================================
# Operator Groups — multinational parent companies
# ============================================================================

OPERATOR_GROUPS = {
    "millicom": {
        "group_id": "millicom",
        "group_name": "Millicom International Cellular S.A.",
        "brand_name": "Tigo",
        "headquarters": "Luxembourg",
        "ir_url": "https://www.millicom.com/investors/",
        "stock_ticker": "TIGO (NASDAQ)",
        "markets_count": 11,
        "notes": "Leading provider of mobile and cable services in Latin America",
    },
    "vodafone_group": {
        "group_id": "vodafone_group",
        "group_name": "Vodafone Group Plc",
        "brand_name": "Vodafone",
        "headquarters": "London, UK",
        "ir_url": "https://www.vodafone.com/investors",
        "stock_ticker": "VOD (LSE/NASDAQ)",
        "markets_count": 15,
    },
    "telefonica_group": {
        "group_id": "telefonica_group",
        "group_name": "Telefonica S.A.",
        "brand_name": "Movistar",
        "headquarters": "Madrid, Spain",
        "ir_url": "https://www.telefonica.com/en/shareholders-investors/",
        "stock_ticker": "TEF (BME/NYSE)",
        "markets_count": 12,
    },
    "america_movil": {
        "group_id": "america_movil",
        "group_name": "America Movil S.A.B. de C.V.",
        "brand_name": "Claro",
        "headquarters": "Mexico City, Mexico",
        "ir_url": "https://www.americamovil.com/English/investors/",
        "stock_ticker": "AMX (BMV/NYSE)",
        "markets_count": 25,
    },
    "iliad_group": {
        "group_id": "iliad_group",
        "group_name": "Iliad S.A.",
        "brand_name": "Free / Iliad / Play",
        "headquarters": "Paris, France",
        "ir_url": "https://www.iliad.fr/en/finances",
        "stock_ticker": "ILD (Euronext Paris)",
        "markets_count": 3,
        "notes": "Founded by Xavier Niel. Operates Free (France), Iliad (Italy), Play (Poland). NJJ Holding (Niel's personal vehicle) also controls Salt (Switzerland), eir (Ireland), lifecell (Ukraine), Monaco Telecom (Monaco/Cyprus/Malta).",
    },
    "njj_holding": {
        "group_id": "njj_holding",
        "group_name": "NJJ Holding S.A.S.",
        "brand_name": "Salt / eir / lifecell / Monaco Telecom / Epic",
        "headquarters": "Paris, France",
        "ir_url": "",
        "stock_ticker": "Private",
        "markets_count": 7,
        "notes": "Xavier Niel's personal investment vehicle. Controls Salt (Switzerland), eir (Ireland), lifecell+Datagroup-Volia (Ukraine), Monaco Telecom (Monaco/Cyprus/Malta). Also majority shareholder of Iliad SA.",
    },
    "ck_hutchison_telecom": {
        "group_id": "ck_hutchison_telecom",
        "group_name": "CK Hutchison Networks",
        "brand_name": "Three / 3",
        "headquarters": "Hong Kong",
        "ir_url": "https://www.ckhutchisontelecom.com/en/ir/",
        "stock_ticker": "CKH (HKEX: 0001)",
        "markets_count": 6,
        "notes": "European telecom portfolio under strategic review. Operates Three in UK, Ireland, Italy, Sweden, Denmark, Austria.",
    },
    "veon_group": {
        "group_id": "veon_group",
        "group_name": "VEON Ltd.",
        "brand_name": "Kyivstar / Beeline / Jazz",
        "headquarters": "Amsterdam, Netherlands",
        "ir_url": "https://www.veon.com/investors/",
        "stock_ticker": "VEON (NASDAQ)",
        "markets_count": 6,
        "notes": "Operates Kyivstar (Ukraine), Beeline (Kazakhstan, Uzbekistan, Kyrgyzstan), Jazz (Pakistan), Banglalink (Bangladesh).",
    },
    "neqsol_holding": {
        "group_id": "neqsol_holding",
        "group_name": "NEQSOL Holding",
        "brand_name": "Vodafone Ukraine / Bakcell",
        "headquarters": "Baku, Azerbaijan",
        "ir_url": "",
        "stock_ticker": "Private",
        "markets_count": 3,
        "notes": "Azerbaijani conglomerate. Acquired Vodafone Ukraine from MTS in 2019. Also owns Bakcell (Azerbaijan), Activ (Georgia).",
    },
    "monaco_telecom": {
        "group_id": "monaco_telecom",
        "group_name": "Monaco Telecom S.A.M.",
        "brand_name": "Monaco Telecom / Epic",
        "headquarters": "Monaco",
        "ir_url": "",
        "stock_ticker": "Private (NJJ subsidiary)",
        "markets_count": 3,
        "notes": "NJJ subsidiary. Operates Monaco Telecom (Monaco), Epic (Cyprus), Epic (Malta).",
    },
    "orange_group": {
        "group_id": "orange_group",
        "group_name": "Orange S.A.",
        "brand_name": "Orange",
        "headquarters": "Paris, France",
        "ir_url": "https://www.orange.com/en/investors",
        "stock_ticker": "ORA (Euronext Paris)",
        "markets_count": 26,
    },
    "deutsche_telekom_group": {
        "group_id": "deutsche_telekom_group",
        "group_name": "Deutsche Telekom AG",
        "brand_name": "T-Mobile / Magenta",
        "headquarters": "Bonn, Germany",
        "ir_url": "https://www.telekom.com/en/investor-relations",
        "stock_ticker": "DTE (XETRA)",
        "markets_count": 12,
    },
}

# ============================================================================
# Operator Directory — all registered operators
# ============================================================================

OPERATOR_DIRECTORY = {
    "vodafone_germany": {
        "display_name": "Vodafone Germany",
        "parent_company": "Vodafone Group",
        "country": "Germany",
        "region": "Europe",
        "market": "germany",
        "operator_type": "challenger",
        "ir_url": "https://www.vodafone.com/investors",
        "fiscal_year_start_month": 4,
        "fiscal_year_label": "FY",
        "quarter_naming": "fiscal",
        "currency": "EUR",
    },
    "deutsche_telekom": {
        "display_name": "Deutsche Telekom",
        "parent_company": "Deutsche Telekom AG",
        "country": "Germany",
        "region": "Europe",
        "market": "germany",
        "operator_type": "incumbent",
        "ir_url": "https://www.telekom.com/en/investor-relations",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
    },
    "telefonica_o2": {
        "display_name": "Telefonica O2 Germany",
        "parent_company": "Telefonica SA",
        "country": "Germany",
        "region": "Europe",
        "market": "germany",
        "operator_type": "challenger",
        "ir_url": "https://www.telefonica.de/investor-relations.html",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
    },
    "one_and_one": {
        "display_name": "1&1 AG",
        "parent_company": "United Internet AG",
        "country": "Germany",
        "region": "Europe",
        "market": "germany",
        "operator_type": "new_entrant",
        "ir_url": "https://www.1und1.ag/investor-relations",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
    },

    # ========================================================================
    # Guatemala
    # ========================================================================
    "tigo_guatemala": {
        "display_name": "Tigo Guatemala",
        "parent_company": "Millicom International Cellular",
        "country": "Guatemala",
        "region": "Latin America",
        "market": "guatemala",
        "operator_type": "incumbent",
        "group_id": "millicom",
        "ir_url": "https://www.millicom.com/investors/",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "GTQ",
    },
    "claro_gt": {
        "display_name": "Claro Guatemala",
        "parent_company": "America Movil",
        "country": "Guatemala",
        "region": "Latin America",
        "market": "guatemala",
        "operator_type": "challenger",
        "group_id": "america_movil",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "GTQ",
    },
    "movistar_gt": {
        "display_name": "Movistar Guatemala",
        "parent_company": "Telefonica S.A.",
        "country": "Guatemala",
        "region": "Latin America",
        "market": "guatemala",
        "operator_type": "challenger",
        "group_id": "telefonica_group",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "GTQ",
    },

    # ========================================================================
    # Honduras
    # ========================================================================
    "tigo_honduras": {
        "display_name": "Tigo Honduras",
        "parent_company": "Millicom International Cellular",
        "country": "Honduras",
        "region": "Latin America",
        "market": "honduras",
        "operator_type": "incumbent",
        "group_id": "millicom",
        "ir_url": "https://www.millicom.com/investors/",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "HNL",
    },
    "claro_hn": {
        "display_name": "Claro Honduras",
        "parent_company": "America Movil",
        "country": "Honduras",
        "region": "Latin America",
        "market": "honduras",
        "operator_type": "challenger",
        "group_id": "america_movil",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "HNL",
    },
    "digicel_hn": {
        "display_name": "Digicel Honduras",
        "parent_company": "Digicel Group",
        "country": "Honduras",
        "region": "Latin America",
        "market": "honduras",
        "operator_type": "challenger",
        "fiscal_year_start_month": 4,
        "quarter_naming": "fiscal",
        "currency": "HNL",
    },

    # ========================================================================
    # El Salvador
    # ========================================================================
    "tigo_el_salvador": {
        "display_name": "Tigo El Salvador",
        "parent_company": "Millicom International Cellular",
        "country": "El Salvador",
        "region": "Latin America",
        "market": "el_salvador",
        "operator_type": "challenger",
        "group_id": "millicom",
        "ir_url": "https://www.millicom.com/investors/",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "USD",
    },
    "claro_sv": {
        "display_name": "Claro El Salvador",
        "parent_company": "America Movil",
        "country": "El Salvador",
        "region": "Latin America",
        "market": "el_salvador",
        "operator_type": "incumbent",
        "group_id": "america_movil",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "USD",
    },
    "digicel_sv": {
        "display_name": "Digicel El Salvador",
        "parent_company": "Digicel Group",
        "country": "El Salvador",
        "region": "Latin America",
        "market": "el_salvador",
        "operator_type": "challenger",
        "fiscal_year_start_month": 4,
        "quarter_naming": "fiscal",
        "currency": "USD",
    },

    # ========================================================================
    # Colombia
    # ========================================================================
    "tigo_colombia": {
        "display_name": "Tigo Colombia",
        "parent_company": "Millicom International Cellular",
        "country": "Colombia",
        "region": "Latin America",
        "market": "colombia",
        "operator_type": "challenger",
        "group_id": "millicom",
        "ir_url": "https://www.millicom.com/investors/",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "COP",
    },
    "claro_co": {
        "display_name": "Claro Colombia",
        "parent_company": "America Movil",
        "country": "Colombia",
        "region": "Latin America",
        "market": "colombia",
        "operator_type": "incumbent",
        "group_id": "america_movil",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "COP",
    },
    "movistar_co": {
        "display_name": "Movistar Colombia",
        "parent_company": "Telefonica S.A.",
        "country": "Colombia",
        "region": "Latin America",
        "market": "colombia",
        "operator_type": "challenger",
        "group_id": "telefonica_group",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "COP",
    },
    "wom_co": {
        "display_name": "WOM Colombia",
        "parent_company": "WOM S.A.",
        "country": "Colombia",
        "region": "Latin America",
        "market": "colombia",
        "operator_type": "new_entrant",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "COP",
    },

    # ========================================================================
    # Panama
    # ========================================================================
    "tigo_panama": {
        "display_name": "Tigo Panama",
        "parent_company": "Millicom International Cellular",
        "country": "Panama",
        "region": "Latin America",
        "market": "panama",
        "operator_type": "challenger",
        "group_id": "millicom",
        "ir_url": "https://www.millicom.com/investors/",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "USD",
    },
    "claro_pa": {
        "display_name": "Claro Panama",
        "parent_company": "America Movil",
        "country": "Panama",
        "region": "Latin America",
        "market": "panama",
        "operator_type": "incumbent",
        "group_id": "america_movil",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "USD",
    },
    "digicel_pa": {
        "display_name": "Digicel Panama",
        "parent_company": "Digicel Group",
        "country": "Panama",
        "region": "Latin America",
        "market": "panama",
        "operator_type": "challenger",
        "fiscal_year_start_month": 4,
        "quarter_naming": "fiscal",
        "currency": "USD",
    },

    # ========================================================================
    # Bolivia
    # ========================================================================
    "tigo_bolivia": {
        "display_name": "Tigo Bolivia",
        "parent_company": "Millicom International Cellular",
        "country": "Bolivia",
        "region": "Latin America",
        "market": "bolivia",
        "operator_type": "incumbent",
        "group_id": "millicom",
        "ir_url": "https://www.millicom.com/investors/",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "BOB",
    },
    "entel_bo": {
        "display_name": "Entel Bolivia",
        "parent_company": "Entel S.A. (State-owned)",
        "country": "Bolivia",
        "region": "Latin America",
        "market": "bolivia",
        "operator_type": "incumbent",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "BOB",
    },
    "viva_bo": {
        "display_name": "Viva Bolivia",
        "parent_company": "NuevaTel PCS",
        "country": "Bolivia",
        "region": "Latin America",
        "market": "bolivia",
        "operator_type": "challenger",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "BOB",
    },

    # ========================================================================
    # Paraguay
    # ========================================================================
    "tigo_paraguay": {
        "display_name": "Tigo Paraguay",
        "parent_company": "Millicom International Cellular",
        "country": "Paraguay",
        "region": "Latin America",
        "market": "paraguay",
        "operator_type": "incumbent",
        "group_id": "millicom",
        "ir_url": "https://www.millicom.com/investors/",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "PYG",
    },
    "claro_py": {
        "display_name": "Claro Paraguay",
        "parent_company": "America Movil",
        "country": "Paraguay",
        "region": "Latin America",
        "market": "paraguay",
        "operator_type": "challenger",
        "group_id": "america_movil",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "PYG",
    },
    "personal_py": {
        "display_name": "Personal Paraguay",
        "parent_company": "Telecom Argentina (Grupo Clarin)",
        "country": "Paraguay",
        "region": "Latin America",
        "market": "paraguay",
        "operator_type": "challenger",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "PYG",
    },

    # ========================================================================
    # Nicaragua
    # ========================================================================
    "tigo_nicaragua": {
        "display_name": "Tigo Nicaragua",
        "parent_company": "Millicom International Cellular",
        "country": "Nicaragua",
        "region": "Latin America",
        "market": "nicaragua",
        "operator_type": "incumbent",
        "group_id": "millicom",
        "ir_url": "https://www.millicom.com/investors/",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "NIO",
    },
    "claro_ni": {
        "display_name": "Claro Nicaragua",
        "parent_company": "America Movil",
        "country": "Nicaragua",
        "region": "Latin America",
        "market": "nicaragua",
        "operator_type": "challenger",
        "group_id": "america_movil",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "NIO",
    },

    # ========================================================================
    # Ecuador
    # ========================================================================
    "tigo_ecuador": {
        "display_name": "Tigo Ecuador",
        "parent_company": "Millicom International Cellular",
        "country": "Ecuador",
        "region": "Latin America",
        "market": "ecuador",
        "operator_type": "challenger",
        "group_id": "millicom",
        "ir_url": "https://www.millicom.com/investors/",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "USD",
        "notes": "Acquired 2025. Formerly Telefonica Ecuador.",
    },
    "claro_ec": {
        "display_name": "Claro Ecuador",
        "parent_company": "America Movil",
        "country": "Ecuador",
        "region": "Latin America",
        "market": "ecuador",
        "operator_type": "incumbent",
        "group_id": "america_movil",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "USD",
    },
    "cnt_ec": {
        "display_name": "CNT Ecuador",
        "parent_company": "Corporacion Nacional de Telecomunicaciones (State-owned)",
        "country": "Ecuador",
        "region": "Latin America",
        "market": "ecuador",
        "operator_type": "incumbent",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "USD",
    },

    # ========================================================================
    # Uruguay
    # ========================================================================
    "tigo_uruguay": {
        "display_name": "Tigo Uruguay",
        "parent_company": "Millicom International Cellular",
        "country": "Uruguay",
        "region": "Latin America",
        "market": "uruguay",
        "operator_type": "challenger",
        "group_id": "millicom",
        "ir_url": "https://www.millicom.com/investors/",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "UYU",
        "notes": "Acquired 2025. New market entry.",
    },
    "antel_uy": {
        "display_name": "Antel Uruguay",
        "parent_company": "Administracion Nacional de Telecomunicaciones (State-owned)",
        "country": "Uruguay",
        "region": "Latin America",
        "market": "uruguay",
        "operator_type": "incumbent",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "UYU",
    },
    "claro_uy": {
        "display_name": "Claro Uruguay",
        "parent_company": "America Movil",
        "country": "Uruguay",
        "region": "Latin America",
        "market": "uruguay",
        "operator_type": "challenger",
        "group_id": "america_movil",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "UYU",
    },

    # ========================================================================
    # Chile
    # ========================================================================
    "tigo_chile": {
        "display_name": "Tigo Chile",
        "parent_company": "Millicom International Cellular",
        "country": "Chile",
        "region": "Latin America",
        "market": "chile",
        "operator_type": "challenger",
        "group_id": "millicom",
        "ir_url": "https://www.millicom.com/investors/",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "CLP",
        "notes": "Acquired Telefonica Chile Feb 2026. No historical Tigo data.",
    },
    "entel_cl": {
        "display_name": "Entel Chile",
        "parent_company": "Entel S.A.",
        "country": "Chile",
        "region": "Latin America",
        "market": "chile",
        "operator_type": "incumbent",
        "ir_url": "https://investors.entel.cl/",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "CLP",
    },
    "wom_cl": {
        "display_name": "WOM Chile",
        "parent_company": "WOM S.A.",
        "country": "Chile",
        "region": "Latin America",
        "market": "chile",
        "operator_type": "challenger",
        "ir_url": "https://www.wom.cl/",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "CLP",
    },
    "claro_cl": {
        "display_name": "Claro Chile",
        "parent_company": "America Movil",
        "country": "Chile",
        "region": "Latin America",
        "market": "chile",
        "operator_type": "challenger",
        "group_id": "america_movil",
        "ir_url": "https://www.americamovil.com/English/investors/",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "CLP",
    },
    "movistar_cl": {
        "display_name": "Movistar Chile",
        "parent_company": "Telefonica S.A.",
        "country": "Chile",
        "region": "Latin America",
        "market": "chile",
        "operator_type": "incumbent",
        "group_id": "telefonica_group",
        "ir_url": "https://www.telefonica.com/en/shareholders-investors/",
        "fiscal_year_start_month": 1,
        "quarter_naming": "calendar",
        "currency": "CLP",
    },

    # ========================================================================
    # Netherlands
    # ========================================================================
    "odido_nl": {
        "display_name": "Odido",
        "parent_company": "Odido Group (Apax/Warburg Pincus)",
        "country": "Netherlands",
        "region": "Europe",
        "market": "netherlands",
        "operator_type": "challenger",
        "ir_url": "https://www.odido.nl/",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
        "notes": "Rebranded from T-Mobile Netherlands in Sep 2023. Sold by Deutsche Telekom to Apax/Warburg Pincus consortium.",
    },
    "kpn_nl": {
        "display_name": "KPN",
        "parent_company": "Koninklijke KPN N.V.",
        "country": "Netherlands",
        "region": "Europe",
        "market": "netherlands",
        "operator_type": "incumbent",
        "ir_url": "https://www.kpn.com/investor-relations.htm",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
    },
    "vodafoneziggo_nl": {
        "display_name": "VodafoneZiggo",
        "parent_company": "VodafoneZiggo Group (Vodafone/Liberty Global JV)",
        "country": "Netherlands",
        "region": "Europe",
        "market": "netherlands",
        "operator_type": "challenger",
        "group_id": "vodafone_group",
        "ir_url": "https://www.vodafoneziggo.nl/",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
    },

    # ========================================================================
    # Belgium
    # ========================================================================
    "proximus_be": {
        "display_name": "Proximus",
        "parent_company": "Proximus Group",
        "country": "Belgium",
        "region": "Europe",
        "market": "belgium",
        "operator_type": "incumbent",
        "ir_url": "https://www.proximus.com/investors",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
    },
    "orange_be": {
        "display_name": "Orange Belgium",
        "parent_company": "Orange S.A.",
        "country": "Belgium",
        "region": "Europe",
        "market": "belgium",
        "operator_type": "challenger",
        "ir_url": "https://corporate.orange.be/en/investors",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
    },
    "telenet_be": {
        "display_name": "Telenet",
        "parent_company": "Liberty Global (via Telenet Group)",
        "country": "Belgium",
        "region": "Europe",
        "market": "belgium",
        "operator_type": "challenger",
        "ir_url": "https://www2.telenet.be/en/investor-relations/",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
        "notes": "Cable operator, also owns BASE mobile brand. Acquired VOO (Wallonia cable) in 2023.",
    },

    # ========================================================================
    # France
    # ========================================================================
    "free_fr": {
        "display_name": "Free (Iliad)",
        "parent_company": "Iliad S.A.",
        "country": "France",
        "region": "Europe",
        "market": "france",
        "operator_type": "challenger",
        "group_id": "iliad_group",
        "ir_url": "https://www.iliad.fr/en/finances",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
    },
    "orange_fr": {
        "display_name": "Orange France",
        "parent_company": "Orange S.A.",
        "country": "France",
        "region": "Europe",
        "market": "france",
        "operator_type": "incumbent",
        "group_id": "orange_group",
        "ir_url": "https://www.orange.com/en/investors",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
    },
    "sfr_fr": {
        "display_name": "SFR (Altice France)",
        "parent_company": "Altice France / SFR Group",
        "country": "France",
        "region": "Europe",
        "market": "france",
        "operator_type": "challenger",
        "ir_url": "https://www.altice.net/investors",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
        "notes": "EUR 21.2B debt. Under financial restructuring. Patrick Drahi facing asset disposals.",
    },
    "bouygues_telecom_fr": {
        "display_name": "Bouygues Telecom",
        "parent_company": "Bouygues S.A.",
        "country": "France",
        "region": "Europe",
        "market": "france",
        "operator_type": "challenger",
        "ir_url": "https://www.bouygues.com/en/investors/",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
        "notes": "Consolidated La Poste Mobile from Q4 2024.",
    },

    # ========================================================================
    # Italy
    # ========================================================================
    "iliad_it": {
        "display_name": "Iliad Italia",
        "parent_company": "Iliad S.A.",
        "country": "Italy",
        "region": "Europe",
        "market": "italy",
        "operator_type": "challenger",
        "group_id": "iliad_group",
        "ir_url": "https://www.iliad.fr/en/finances",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
        "notes": "Entered Italy June 2018. Fastest-growing European operator.",
    },
    "tim_it": {
        "display_name": "TIM (Telecom Italia)",
        "parent_company": "TIM S.p.A.",
        "country": "Italy",
        "region": "Europe",
        "market": "italy",
        "operator_type": "incumbent",
        "ir_url": "https://www.gruppotim.it/en/investors.html",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
        "notes": "Sold NetCo (fixed network) to KKR July 2024. Now asset-light services company.",
    },
    "vodafone_it": {
        "display_name": "Vodafone Italia / Fastweb",
        "parent_company": "Swisscom AG (acquired Jan 2025)",
        "country": "Italy",
        "region": "Europe",
        "market": "italy",
        "operator_type": "challenger",
        "ir_url": "https://www.swisscom.ch/en/about/investors.html",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
        "notes": "Swisscom completed acquisition of Vodafone Italia Jan 2025. Fastweb integration ongoing.",
    },
    "windtre_it": {
        "display_name": "WindTre",
        "parent_company": "CK Hutchison Holdings",
        "country": "Italy",
        "region": "Europe",
        "market": "italy",
        "operator_type": "challenger",
        "ir_url": "https://www.ckh.com.hk/en/investors/",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
        "notes": "CK Hutchison evaluating sale of European telecom assets.",
    },

    # ========================================================================
    # Poland
    # ========================================================================
    "play_pl": {
        "display_name": "Play (Iliad Poland)",
        "parent_company": "Iliad S.A. (via P4 sp. z o.o.)",
        "country": "Poland",
        "region": "Europe",
        "market": "poland",
        "operator_type": "challenger",
        "group_id": "iliad_group",
        "ir_url": "https://www.iliad.fr/en/finances",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "PLN",
        "notes": "Poland's #1 mobile operator by subscribers. Acquired by Iliad 2020.",
    },
    "orange_pl": {
        "display_name": "Orange Polska",
        "parent_company": "Orange S.A.",
        "country": "Poland",
        "region": "Europe",
        "market": "poland",
        "operator_type": "incumbent",
        "group_id": "orange_group",
        "ir_url": "https://www.orange.pl/investor-relations",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "PLN",
    },
    "tmobile_pl": {
        "display_name": "T-Mobile Polska",
        "parent_company": "Deutsche Telekom AG",
        "country": "Poland",
        "region": "Europe",
        "market": "poland",
        "operator_type": "challenger",
        "group_id": "deutsche_telekom_group",
        "ir_url": "https://www.telekom.com/en/investor-relations",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "PLN",
    },
    "plus_pl": {
        "display_name": "Plus (Polkomtel / Cyfrowy Polsat)",
        "parent_company": "Cyfrowy Polsat S.A. (Polsat Plus Group)",
        "country": "Poland",
        "region": "Europe",
        "market": "poland",
        "operator_type": "challenger",
        "ir_url": "https://grupapolsatplus.pl/en/investor-relations",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "PLN",
        "notes": "Part of Cyfrowy Polsat media-telecom conglomerate (Polsat TV + Plus + Netia).",
    },
    # ---- Switzerland ----
    "salt_ch": {
        "display_name": "Salt Mobile",
        "parent_company": "NJJ Holding (Matterhorn Telecom)",
        "country": "Switzerland",
        "region": "Europe",
        "market": "switzerland",
        "operator_type": "challenger",
        "group_id": "njj_holding",
        "ir_url": "https://www.salt.ch/en/about/investors-relations",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "CHF",
        "notes": "NJJ/Xavier Niel owned. Private company (Matterhorn Telecom). ~60% EBITDA margin, highest in Europe. #3 mobile in Switzerland.",
    },
    "swisscom_ch": {
        "display_name": "Swisscom",
        "parent_company": "Swisscom AG (51% Swiss Confederation)",
        "country": "Switzerland",
        "region": "Europe",
        "market": "switzerland",
        "operator_type": "incumbent",
        "ir_url": "https://www.swisscom.ch/en/about/investors.html",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "CHF",
        "notes": "Switzerland's dominant incumbent. 51% state-owned (Swiss Confederation). Acquired Vodafone Italia Dec 2024 (EUR 8B).",
    },
    "sunrise_ch": {
        "display_name": "Sunrise",
        "parent_company": "Sunrise Communications AG (spun off from Liberty Global Nov 2024)",
        "country": "Switzerland",
        "region": "Europe",
        "market": "switzerland",
        "operator_type": "challenger",
        "ir_url": "https://www.sunrise.ch/en/corporate/investors",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "CHF",
        "notes": "Merged Sunrise+UPC. Listed on SIX (SUNN) and NASDAQ (SNRE) since Nov 2024. Mike Fries (Liberty Global) as Chairman.",
    },
    # ---- Ireland ----
    "eir_ie": {
        "display_name": "eir",
        "parent_company": "NJJ Holding (>70%)",
        "country": "Ireland",
        "region": "Europe",
        "market": "ireland",
        "operator_type": "incumbent",
        "group_id": "njj_holding",
        "ir_url": "https://www.eir.ie/investorrelations/",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
        "notes": "Ireland's fixed-line incumbent. NJJ >70% ownership. 2.2M premises FTTH/FTTC coverage (95% of Ireland).",
    },
    "three_ie": {
        "display_name": "Three Ireland",
        "parent_company": "CK Hutchison",
        "country": "Ireland",
        "region": "Europe",
        "market": "ireland",
        "operator_type": "leader",
        "group_id": "ck_hutchison_telecom",
        "ir_url": "https://www.ckhutchisontelecom.com/en/ir/",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
        "notes": "Ireland's #1 mobile operator (~48% share incl M2M). CK Hutchison in talks to sell to Liberty Global for EUR 1.5B.",
    },
    "vodafone_ie": {
        "display_name": "Vodafone Ireland",
        "parent_company": "Vodafone Group",
        "country": "Ireland",
        "region": "Europe",
        "market": "ireland",
        "operator_type": "challenger",
        "group_id": "vodafone_group",
        "ir_url": "https://www.vodafone.com/investors",
        "fiscal_year_start_month": 4,
        "fiscal_year_label": "FY",
        "quarter_naming": "fiscal",
        "currency": "EUR",
        "notes": "Vodafone Group subsidiary. SIRO JV (50/50 with ESB) for fiber. 3G shutdown completed Nov 2024.",
    },
    # ---- Ukraine ----
    "lifecell_ua": {
        "display_name": "lifecell (DVL Group)",
        "parent_company": "NJJ Holding / DVL Group",
        "country": "Ukraine",
        "region": "Europe",
        "market": "ukraine",
        "operator_type": "challenger",
        "group_id": "njj_holding",
        "ir_url": "",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "UAH",
        "notes": "NJJ acquired Sep 2024 for $524M. Merged with Datagroup-Volia (#1 fixed ISP). EBRD/IFC $435M financing. Ukraine's first converged telco.",
    },
    "kyivstar_ua": {
        "display_name": "Kyivstar",
        "parent_company": "VEON Ltd.",
        "country": "Ukraine",
        "region": "Europe",
        "market": "ukraine",
        "operator_type": "leader",
        "group_id": "veon_group",
        "ir_url": "https://www.veon.com/kyivstar",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "UAH",
        "notes": "Ukraine's #1 mobile operator (~24M subs). NASDAQ listing as KYIV (Aug 2025). Suffered major cyberattack Dec 2023.",
    },
    "vodafone_ua": {
        "display_name": "Vodafone Ukraine",
        "parent_company": "NEQSOL Holding",
        "country": "Ukraine",
        "region": "Europe",
        "market": "ukraine",
        "operator_type": "challenger",
        "group_id": "neqsol_holding",
        "ir_url": "",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "UAH",
        "notes": "NEQSOL Holding (Azerbaijan) acquired from MTS 2019. Vodafone brand license. ~15.8M mobile subs. Growing GPON fiber.",
    },
    # ---- Cyprus ----
    "epic_cy": {
        "display_name": "Epic Cyprus",
        "parent_company": "Monaco Telecom (NJJ)",
        "country": "Cyprus",
        "region": "Europe",
        "market": "cyprus",
        "operator_type": "challenger",
        "group_id": "monaco_telecom",
        "ir_url": "https://www.epic.com.cy",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
        "notes": "Monaco Telecom subsidiary. #2 mobile in Cyprus (~35%). 5G pioneer (Jul 2021). Fastest network (Ookla).",
    },
    "cyta_cy": {
        "display_name": "Cyta",
        "parent_company": "Republic of Cyprus (100% state-owned)",
        "country": "Cyprus",
        "region": "Europe",
        "market": "cyprus",
        "operator_type": "incumbent",
        "ir_url": "https://www.cyta.com.cy",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
        "notes": "Semi-governmental incumbent. ~52% mobile share. Cytamobile-Vodafone mobile brand. FTTP 77% coverage.",
    },
    "primetel_cy": {
        "display_name": "PrimeTel",
        "parent_company": "MP Cyprus Holdings",
        "country": "Cyprus",
        "region": "Europe",
        "market": "cyprus",
        "operator_type": "challenger",
        "ir_url": "",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
        "notes": "Smallest MNO in Cyprus (~13% mobile share). Broadband and TV competitor.",
    },
    # ---- Malta ----
    "epic_mt": {
        "display_name": "Epic Malta",
        "parent_company": "Monaco Telecom (NJJ)",
        "country": "Malta",
        "region": "Europe",
        "market": "malta",
        "operator_type": "challenger",
        "group_id": "monaco_telecom",
        "ir_url": "",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
        "notes": "Monaco Telecom subsidiary. Smallest operator in Malta (~15-20% mobile). Mobile-centric.",
    },
    "go_mt": {
        "display_name": "GO plc",
        "parent_company": "GO plc (listed Malta Stock Exchange)",
        "country": "Malta",
        "region": "Europe",
        "market": "malta",
        "operator_type": "incumbent",
        "ir_url": "https://www.go.com.mt/investor-centre/",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
        "notes": "Malta's fixed-line incumbent. Revenue EUR 244.9M FY2024. 34.8% mobile, 46.8% broadband. Cablenet Cyprus subsidiary.",
    },
    "melita_mt": {
        "display_name": "Melita",
        "parent_company": "EQT (Swedish PE)",
        "country": "Malta",
        "region": "Europe",
        "market": "malta",
        "operator_type": "challenger",
        "ir_url": "",
        "fiscal_year_start_month": 1,
        "fiscal_year_label": "",
        "quarter_naming": "calendar",
        "currency": "EUR",
        "notes": "EQT PE-owned since 2019. Cable/HFC + mobile operator. Strong TV subscriber base. #2 in Malta.",
    },
}

# Earnings release calendar
EARNINGS_CALENDAR = {
    "vodafone_germany": {
        "Q3 FY26": {"expected_date": "2026-02-05", "status": "published"},
        "Q2 FY26": {"expected_date": "2025-11-12", "status": "published"},
        "Q1 FY26": {"expected_date": "2025-07-25", "status": "published"},
        "Q4 FY25": {"expected_date": "2025-05-20", "status": "published"},
        "Q3 FY25": {"expected_date": "2025-01-28", "status": "published"},
        "Q2 FY25": {"expected_date": "2024-11-12", "status": "published"},
        "Q1 FY25": {"expected_date": "2024-07-23", "status": "published"},
        "Q4 FY24": {"expected_date": "2024-05-21", "status": "published"},
    },
    "deutsche_telekom": {
        "Q4 2025": {"expected_date": "2026-02-27", "status": "pending"},
        "Q3 2025": {"expected_date": "2025-11-14", "status": "published"},
        "Q2 2025": {"expected_date": "2025-08-08", "status": "published"},
        "Q1 2025": {"expected_date": "2025-05-15", "status": "published"},
        "Q4 2024": {"expected_date": "2025-02-27", "status": "published"},
        "Q3 2024": {"expected_date": "2024-11-14", "status": "published"},
        "Q2 2024": {"expected_date": "2024-08-08", "status": "published"},
        "Q1 2024": {"expected_date": "2024-05-16", "status": "published"},
    },
    "telefonica_o2": {
        "Q3 2025": {"expected_date": "2025-10-30", "status": "published"},
        "Q2 2025": {"expected_date": "2025-07-24", "status": "published"},
        "Q1 2025": {"expected_date": "2025-05-08", "status": "published"},
        "Q4 2024": {"expected_date": "2025-02-20", "status": "published"},
        "Q3 2024": {"expected_date": "2024-10-24", "status": "published"},
        "Q2 2024": {"expected_date": "2024-07-25", "status": "published"},
        "Q1 2024": {"expected_date": "2024-05-09", "status": "published"},
    },
    "one_and_one": {
        "Q3 2025": {"expected_date": "2025-11-13", "status": "published"},
        "Q2 2025": {"expected_date": "2025-08-14", "status": "published"},
        "Q1 2025": {"expected_date": "2025-05-15", "status": "published"},
        "Q4 2024": {"expected_date": "2025-03-27", "status": "published"},
        "Q3 2024": {"expected_date": "2024-11-14", "status": "published"},
        "Q2 2024": {"expected_date": "2024-08-08", "status": "published"},
        "Q1 2024": {"expected_date": "2024-05-16", "status": "published"},
    },
}


def get_operators_for_market(market: str) -> list:
    """Get all operator IDs for a given market."""
    return [
        op_id for op_id, info in OPERATOR_DIRECTORY.items()
        if info["market"] == market
    ]


def get_operator_info(operator_id: str) -> dict:
    """Get operator metadata by ID. Returns empty dict if not found."""
    return OPERATOR_DIRECTORY.get(operator_id, {})


def get_operators_for_group(group_id: str) -> list:
    """Get all operator IDs belonging to a given group."""
    return [
        op_id for op_id, info in OPERATOR_DIRECTORY.items()
        if info.get("group_id") == group_id
    ]


def get_group_info(group_id: str) -> dict:
    """Get group metadata by ID. Returns empty dict if not found."""
    return OPERATOR_GROUPS.get(group_id, {})


def get_all_markets() -> list[str]:
    """Get all unique market IDs."""
    return sorted(set(info["market"] for info in OPERATOR_DIRECTORY.values()))


def get_non_group_operators(market: str, group_id: str) -> list[str]:
    """Get operator IDs in a market that do NOT belong to a given group."""
    return [
        op_id for op_id, info in OPERATOR_DIRECTORY.items()
        if info["market"] == market and info.get("group_id") != group_id
    ]
